version: '3.7'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # needed because of issue with react-scripts https://github.com/facebook/create-react-app/issues/8688
