version: '3.7'

services:

  app-nodejs:
    container_name: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    volumes:
      - '/app/node_modules'
      - './app:/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true # needed because of issue with react-scripts https://github.com/facebook/create-react-app/issues/8688

  sql-postgres:
    image: postgres:12.0-alpine
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}

  db-django:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    volumes:
      - ./db:/db
    ports:
      - "8000:8000"
    depends_on:
      - sql-postgres
    env_file: 
      - ./.env
  
