name: Deploy master
on:
  push:
    branches:
    - master
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: cd ./app && zip -r app_deploy.zip . -x "*.git*" "./infra/*" "./node_modules/*"
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v13
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: us-dev-dev-vpc
        environment_name: us-dev-dev-vpc
        version_label: 0.0.5
        region: eu-west-1
        deployment_package: ./app/app_deploy.zip
